/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 *

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)
*/
/*GtkWidget*
create_CfgWnd (void)
{
  GtkWidget *CfgWnd;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment4;
  GtkWidget *table1;
  GtkWidget *label1v;
  GtkWidget *label9;
  GtkWidget *cbVolume;
  GList *cbVolume_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *cbReverb;
  GList *cbReverb_items = NULL;
  GtkWidget *combo_entry2;
  GtkWidget *cbInterpolation;
  GList *cbInterpolation_items = NULL;
  GtkWidget *combo_entry3;
  GtkWidget *label8;
  GtkWidget *label10;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *vbox3;
  GtkWidget *chkEnableXA;
  GtkWidget *chkXASpeed;
  GtkWidget *label11;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *vbox4;
  GtkWidget *chkHiCompat;
  GtkWidget *chkIRQWait;
  GtkWidget *chkDisStereo;
  GtkWidget *label12;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  CfgWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (CfgWnd), 10);
  gtk_window_set_title (GTK_WINDOW (CfgWnd), _("Configure Sound"));
  gtk_window_set_modal (GTK_WINDOW (CfgWnd), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 6);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (CfgWnd), vbox1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame1), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 6, 6, 12, 12);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment4), table1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 30);

  label1v = gtk_label_new (_("Volume:"));
  gtk_widget_show (label1v);
  gtk_table_attach (GTK_TABLE (table1), label1v, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1v), GTK_JUSTIFY_RIGHT);

  label9 = gtk_label_new (_("Interpolation:"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_RIGHT);

  cbVolume = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cbVolume)->popwin),
                     "GladeParentKey", cbVolume);
  gtk_widget_show (cbVolume);
  gtk_table_attach (GTK_TABLE (table1), cbVolume, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (cbVolume), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (cbVolume), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (cbVolume), TRUE);
  cbVolume_items = g_list_append (cbVolume_items, (gpointer) _("0: low"));
  cbVolume_items = g_list_append (cbVolume_items, (gpointer) _("1: medium"));
  cbVolume_items = g_list_append (cbVolume_items, (gpointer) _("2: loud"));
  cbVolume_items = g_list_append (cbVolume_items, (gpointer) _("3: loudest"));
  gtk_combo_set_popdown_strings (GTK_COMBO (cbVolume), cbVolume_items);
  g_list_free (cbVolume_items);

  combo_entry1 = GTK_COMBO (cbVolume)->entry;
  gtk_widget_show (combo_entry1);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("0: low"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry1), 9679);

  cbReverb = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cbReverb)->popwin),
                     "GladeParentKey", cbReverb);
  gtk_widget_show (cbReverb);
  gtk_table_attach (GTK_TABLE (table1), cbReverb, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (cbReverb), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (cbReverb), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (cbReverb), TRUE);
  cbReverb_items = g_list_append (cbReverb_items, (gpointer) _("0: off"));
  cbReverb_items = g_list_append (cbReverb_items, (gpointer) _("1: simple"));
  cbReverb_items = g_list_append (cbReverb_items, (gpointer) _("2: Playstation"));
  gtk_combo_set_popdown_strings (GTK_COMBO (cbReverb), cbReverb_items);
  g_list_free (cbReverb_items);

  combo_entry2 = GTK_COMBO (cbReverb)->entry;
  gtk_widget_show (combo_entry2);
  gtk_entry_set_text (GTK_ENTRY (combo_entry2), _("0: off"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry2), 9679);

  cbInterpolation = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cbInterpolation)->popwin),
                     "GladeParentKey", cbInterpolation);
  gtk_widget_show (cbInterpolation);
  gtk_table_attach (GTK_TABLE (table1), cbInterpolation, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (cbInterpolation), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (cbInterpolation), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (cbInterpolation), TRUE);
  cbInterpolation_items = g_list_append (cbInterpolation_items, (gpointer) _("0: none"));
  cbInterpolation_items = g_list_append (cbInterpolation_items, (gpointer) _("1: simple"));
  cbInterpolation_items = g_list_append (cbInterpolation_items, (gpointer) _("2: gaussian"));
  cbInterpolation_items = g_list_append (cbInterpolation_items, (gpointer) _("3: cubic"));
  gtk_combo_set_popdown_strings (GTK_COMBO (cbInterpolation), cbInterpolation_items);
  g_list_free (cbInterpolation_items);

  combo_entry3 = GTK_COMBO (cbInterpolation)->entry;
  gtk_widget_show (combo_entry3);
  gtk_entry_set_text (GTK_ENTRY (combo_entry3), _("0: none"));
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry3), 9679);

  label8 = gtk_label_new (_("Reverb:"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_RIGHT);

  label10 = gtk_label_new (_("<b>General</b>"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label10);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 6, 6, 12, 12);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox3);

  chkEnableXA = gtk_check_button_new_with_mnemonic (_("Enable XA"));
  gtk_widget_show (chkEnableXA);
  gtk_box_pack_start (GTK_BOX (vbox3), chkEnableXA, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, chkEnableXA, _("Enable or disable XA music."), NULL);

  chkXASpeed = gtk_check_button_new_with_mnemonic (_("Adjust XA speed"));
  gtk_widget_show (chkXASpeed);
  gtk_box_pack_start (GTK_BOX (vbox3), chkXASpeed, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, chkXASpeed, _("Choose this if XA music is played too quickly."), NULL);

  label11 = gtk_label_new (_("<b>XA Music</b>"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label11);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox1), frame3, TRUE, TRUE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 6, 6, 12, 12);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox4);

  chkHiCompat = gtk_check_button_new_with_mnemonic (_("High compatibility mode"));
  gtk_widget_show (chkHiCompat);
  gtk_box_pack_start (GTK_BOX (vbox4), chkHiCompat, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, chkHiCompat, _("Use the asynchronous SPU interface."), NULL);

  chkIRQWait = gtk_check_button_new_with_mnemonic (_("SPU IRQ Wait"));
  gtk_widget_show (chkIRQWait);
  gtk_box_pack_start (GTK_BOX (vbox4), chkIRQWait, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, chkIRQWait, _("Wait for CPU; only useful for some games."), NULL);

  chkDisStereo = gtk_check_button_new_with_mnemonic (_("Single channel sound"));
  gtk_widget_show (chkDisStereo);
  gtk_box_pack_start (GTK_BOX (vbox4), chkDisStereo, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, chkDisStereo, _("Play only one channel for a performance boost."), NULL);

  label12 = gtk_label_new (_("<b>Compatibility</b>"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label12);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  g_signal_connect ((gpointer) CfgWnd, "destroy",
                    G_CALLBACK (on_CfgWnd_destroy),
                    NULL);

  * Store pointers to all widgets, for use by lookup_widget(). *
  GLADE_HOOKUP_OBJECT_NO_REF (CfgWnd, CfgWnd, "CfgWnd");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (CfgWnd, table1, "table1");
  GLADE_HOOKUP_OBJECT (CfgWnd, label1v, "label1v");
  GLADE_HOOKUP_OBJECT (CfgWnd, label9, "label9");
  GLADE_HOOKUP_OBJECT (CfgWnd, cbVolume, "cbVolume");
  GLADE_HOOKUP_OBJECT (CfgWnd, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (CfgWnd, cbReverb, "cbReverb");
  GLADE_HOOKUP_OBJECT (CfgWnd, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (CfgWnd, cbInterpolation, "cbInterpolation");
  GLADE_HOOKUP_OBJECT (CfgWnd, combo_entry3, "combo_entry3");
  GLADE_HOOKUP_OBJECT (CfgWnd, label8, "label8");
  GLADE_HOOKUP_OBJECT (CfgWnd, label10, "label10");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (CfgWnd, chkEnableXA, "chkEnableXA");
  GLADE_HOOKUP_OBJECT (CfgWnd, chkXASpeed, "chkXASpeed");
  GLADE_HOOKUP_OBJECT (CfgWnd, label11, "label11");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (CfgWnd, chkHiCompat, "chkHiCompat");
  GLADE_HOOKUP_OBJECT (CfgWnd, chkIRQWait, "chkIRQWait");
  GLADE_HOOKUP_OBJECT (CfgWnd, chkDisStereo, "chkDisStereo");
  GLADE_HOOKUP_OBJECT (CfgWnd, label12, "label12");
  GLADE_HOOKUP_OBJECT_NO_REF (CfgWnd, tooltips, "tooltips");

  return CfgWnd;
}

GtkWidget*
create_AboutWnd (void)
{
  GtkWidget *AboutWnd;
  GtkWidget *vbox5;
  GtkWidget *vbox6;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label13;

  AboutWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (AboutWnd), 12);
  gtk_window_set_title (GTK_WINDOW (AboutWnd), _("About Sound Plugin"));
  gtk_window_set_modal (GTK_WINDOW (AboutWnd), TRUE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (AboutWnd), vbox5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Coded by: Pete Bernert and the P.E.Op.S. team"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox6), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);

  label3 = gtk_label_new (_("Homepage: http://home.t-online.de/home/PeteBernert/"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox6), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_CENTER);

  label4 = gtk_label_new (_("EMail: BlackDove@addcom.de"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox6), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_CENTER);

  label5 = gtk_label_new (_("Version: 1.6"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox6), label5, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label5, -1, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_CENTER);

  label6 = gtk_label_new (_("Release date: 05.04.2003"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox6), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_CENTER);

  label13 = gtk_label_new (_("<b>PCSX-df Sound Plugin Adaption</b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (vbox6), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  g_signal_connect ((gpointer) AboutWnd, "destroy",
                    G_CALLBACK (on_AboutWnd_destroy),
                    NULL);

  * Store pointers to all widgets, for use by lookup_widget(). *
  GLADE_HOOKUP_OBJECT_NO_REF (AboutWnd, AboutWnd, "AboutWnd");
  GLADE_HOOKUP_OBJECT (AboutWnd, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (AboutWnd, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (AboutWnd, label2, "label2");
  GLADE_HOOKUP_OBJECT (AboutWnd, label3, "label3");
  GLADE_HOOKUP_OBJECT (AboutWnd, label4, "label4");
  GLADE_HOOKUP_OBJECT (AboutWnd, label5, "label5");
  GLADE_HOOKUP_OBJECT (AboutWnd, label6, "label6");
  GLADE_HOOKUP_OBJECT (AboutWnd, label13, "label13");

  return AboutWnd;
}*/

