/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 *

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_CfgWnd (void)
{
  GtkWidget *CfgWnd;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment4;
  GtkWidget *table1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *resCombo;
  GList *resCombo_items = NULL;
  GtkWidget *entry1;
  GtkWidget *stretchCombo;
  GList *stretchCombo_items = NULL;
  GtkWidget *entry2;
  GtkWidget *ditherCombo;
  GList *ditherCombo_items = NULL;
  GtkWidget *entry3;
  GtkWidget *checkFullscreen;
  GtkWidget *checkScanlines;
  GtkWidget *label10;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *vbox3;
  GtkWidget *checkShowFPS;
  GtkWidget *checkAutoFPSLimit;
  GtkWidget *checkFrameSkip;
  GtkWidget *table2;
  GtkWidget *checkSetFPS;
  GtkWidget *entryFPS;
  GtkWidget *label11;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *vbox4;
  GtkWidget *checkUseFixes;
  GtkWidget *alignment5;
  GtkWidget *table3;
  GtkWidget *checkFix1;
  GtkWidget *checkFix2;
  GtkWidget *checkFix3;
  GtkWidget *checkFix4;
  GtkWidget *checkFix5;
  GtkWidget *checkFix6;
  GtkWidget *checkFix7;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label12;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  CfgWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (CfgWnd), 10);
  gtk_window_set_title (GTK_WINDOW (CfgWnd), _("Configure X11 Video"));
  gtk_window_set_modal (GTK_WINDOW (CfgWnd), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 6);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (CfgWnd), vbox1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame1), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 6, 6, 12, 12);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment4), table1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 30);

  label14 = gtk_label_new (_("Resolution:"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Stretching:"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Dithering:"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  resCombo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (resCombo)->popwin),
                     "GladeParentKey", resCombo);
  gtk_widget_show (resCombo);
  gtk_table_attach (GTK_TABLE (table1), resCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (resCombo), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (resCombo), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (resCombo), TRUE);
  resCombo_items = g_list_append (resCombo_items, (gpointer) _("0: 320x240"));
  resCombo_items = g_list_append (resCombo_items, (gpointer) _("1: 640x480"));
  resCombo_items = g_list_append (resCombo_items, (gpointer) _("2: 800x600"));
  resCombo_items = g_list_append (resCombo_items, (gpointer) _("3: 1024x768"));
  gtk_combo_set_popdown_strings (GTK_COMBO (resCombo), resCombo_items);
  g_list_free (resCombo_items);

  entry1 = GTK_COMBO (resCombo)->entry;
  gtk_widget_show (entry1);
  gtk_tooltips_set_tip (tooltips, entry1, _("Set the size of the screen."), NULL);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("0: 320x240"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  stretchCombo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (stretchCombo)->popwin),
                     "GladeParentKey", stretchCombo);
  gtk_widget_show (stretchCombo);
  gtk_table_attach (GTK_TABLE (table1), stretchCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (stretchCombo), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (stretchCombo), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (stretchCombo), TRUE);
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("0: Full size"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("1: Off"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("2: 2xSal"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("3: 2xSal (unstretched)"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("4: 2xSuperSal"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("5: 2xSuperSal (unstretched)"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("6: SuperEagle"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("7: SuperEagle (unstretched)"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("8: Scale2x"));
  stretchCombo_items = g_list_append (stretchCombo_items, (gpointer) _("9: Scale2x (unstretched)"));
  gtk_combo_set_popdown_strings (GTK_COMBO (stretchCombo), stretchCombo_items);
  g_list_free (stretchCombo_items);

  entry2 = GTK_COMBO (stretchCombo)->entry;
  gtk_widget_show (entry2);
  gtk_tooltips_set_tip (tooltips, entry2, _("These determine how the image is stretched on the screen."), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 9679);

  ditherCombo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (ditherCombo)->popwin),
                     "GladeParentKey", ditherCombo);
  gtk_widget_show (ditherCombo);
  gtk_table_attach (GTK_TABLE (table1), ditherCombo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (ditherCombo), TRUE, FALSE);
  gtk_combo_set_case_sensitive (GTK_COMBO (ditherCombo), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (ditherCombo), TRUE);
  ditherCombo_items = g_list_append (ditherCombo_items, (gpointer) _("0: Off"));
  ditherCombo_items = g_list_append (ditherCombo_items, (gpointer) _("1: Game dependent"));
  ditherCombo_items = g_list_append (ditherCombo_items, (gpointer) _("2: Always"));
  gtk_combo_set_popdown_strings (GTK_COMBO (ditherCombo), ditherCombo_items);
  g_list_free (ditherCombo_items);

  entry3 = GTK_COMBO (ditherCombo)->entry;
  gtk_widget_show (entry3);
  gtk_tooltips_set_tip (tooltips, entry3, _("Select when dithering will occur."), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 9679);

  checkFullscreen = gtk_check_button_new_with_mnemonic (_("Fullscreen"));
  gtk_widget_show (checkFullscreen);
  gtk_table_attach (GTK_TABLE (table1), checkFullscreen, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, checkFullscreen, _("Toggle windowed/fullscreen mode."), NULL);

  checkScanlines = gtk_check_button_new_with_mnemonic (_("Draw scanlines"));
  gtk_widget_show (checkScanlines);
  gtk_table_attach (GTK_TABLE (table1), checkScanlines, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("<b>Screen</b>"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label10);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 6, 6, 12, 12);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox3);

  checkShowFPS = gtk_check_button_new_with_mnemonic (_("Show FPS"));
  gtk_widget_show (checkShowFPS);
  gtk_box_pack_start (GTK_BOX (vbox3), checkShowFPS, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkShowFPS, _("Toggle whether the FPS will be shown."), NULL);

  checkAutoFPSLimit = gtk_check_button_new_with_mnemonic (_("Autodetect FPS limit"));
  gtk_widget_show (checkAutoFPSLimit);
  gtk_box_pack_start (GTK_BOX (vbox3), checkAutoFPSLimit, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkAutoFPSLimit, _("Enable this if games display too quickly."), NULL);

  checkFrameSkip = gtk_check_button_new_with_mnemonic (_("Enable frame skipping"));
  gtk_widget_show (checkFrameSkip);
  gtk_box_pack_start (GTK_BOX (vbox3), checkFrameSkip, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkFrameSkip, _("Skip frames when rendering."), NULL);

  table2 = gtk_table_new (1, 2, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox3), table2, FALSE, FALSE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 12);

  checkSetFPS = gtk_check_button_new_with_mnemonic (_("Set FPS"));
  gtk_widget_show (checkSetFPS);
  gtk_table_attach (GTK_TABLE (table2), checkSetFPS, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entryFPS = gtk_entry_new ();
  gtk_widget_show (entryFPS);
  gtk_table_attach (GTK_TABLE (table2), entryFPS, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entryFPS), 2);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryFPS), 9679);
  gtk_entry_set_width_chars (GTK_ENTRY (entryFPS), 2);

  label11 = gtk_label_new (_("<b>Framerate</b>"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label11);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox1), frame3, TRUE, TRUE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 6, 6, 12, 12);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox4);

  checkUseFixes = gtk_check_button_new_with_mnemonic (_("Use game fixes"));
  gtk_widget_show (checkUseFixes);
  gtk_box_pack_start (GTK_BOX (vbox4), checkUseFixes, FALSE, FALSE, 0);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_box_pack_start (GTK_BOX (vbox4), alignment5, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 19, 0);

  table3 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment5), table3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 16);

  checkFix1 = gtk_check_button_new_with_mnemonic (_("Odd/even bit hack"));
  gtk_widget_show (checkFix1);
  gtk_table_attach (GTK_TABLE (table3), checkFix1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix2 = gtk_check_button_new_with_mnemonic (_("Expand screen width"));
  gtk_widget_show (checkFix2);
  gtk_table_attach (GTK_TABLE (table3), checkFix2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix3 = gtk_check_button_new_with_mnemonic (_("Ignore brightness color"));
  gtk_widget_show (checkFix3);
  gtk_table_attach (GTK_TABLE (table3), checkFix3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix4 = gtk_check_button_new_with_mnemonic (_("Disable coordinate check"));
  gtk_widget_show (checkFix4);
  gtk_table_attach (GTK_TABLE (table3), checkFix4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix5 = gtk_check_button_new_with_mnemonic (_("PC FPS calculation"));
  gtk_widget_show (checkFix5);
  gtk_table_attach (GTK_TABLE (table3), checkFix5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix6 = gtk_check_button_new_with_mnemonic (_("Lazy screen update"));
  gtk_widget_show (checkFix6);
  gtk_table_attach (GTK_TABLE (table3), checkFix6, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkFix7 = gtk_check_button_new_with_mnemonic (_("Old frame skipping"));
  gtk_widget_show (checkFix7);
  gtk_table_attach (GTK_TABLE (table3), checkFix7, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label24 = gtk_label_new (_("Chrono Cross"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table3), label24, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new (_("Capcom fighting games"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table3), label25, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("Black screens in Lunar"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table3), label26, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Compatibility mode"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Better FPS limit in some"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table3), label28, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Pandemonium 2"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table3), label29, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Skip every second frame"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table3), label30, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label12 = gtk_label_new (_("<b>Compatibility</b>"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label12);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  g_signal_connect ((gpointer) CfgWnd, "destroy",
                    G_CALLBACK (on_CfgWnd_destroy),
                    NULL);

  * Store pointers to all widgets, for use by lookup_widget(). *
  GLADE_HOOKUP_OBJECT_NO_REF (CfgWnd, CfgWnd, "CfgWnd");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (CfgWnd, table1, "table1");
  GLADE_HOOKUP_OBJECT (CfgWnd, label14, "label14");
  GLADE_HOOKUP_OBJECT (CfgWnd, label15, "label15");
  GLADE_HOOKUP_OBJECT (CfgWnd, label16, "label16");
  GLADE_HOOKUP_OBJECT (CfgWnd, resCombo, "resCombo");
  GLADE_HOOKUP_OBJECT (CfgWnd, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (CfgWnd, stretchCombo, "stretchCombo");
  GLADE_HOOKUP_OBJECT (CfgWnd, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (CfgWnd, ditherCombo, "ditherCombo");
  GLADE_HOOKUP_OBJECT (CfgWnd, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFullscreen, "checkFullscreen");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkScanlines, "checkScanlines");
  GLADE_HOOKUP_OBJECT (CfgWnd, label10, "label10");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkShowFPS, "checkShowFPS");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkAutoFPSLimit, "checkAutoFPSLimit");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFrameSkip, "checkFrameSkip");
  GLADE_HOOKUP_OBJECT (CfgWnd, table2, "table2");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkSetFPS, "checkSetFPS");
  GLADE_HOOKUP_OBJECT (CfgWnd, entryFPS, "entryFPS");
  GLADE_HOOKUP_OBJECT (CfgWnd, label11, "label11");
  GLADE_HOOKUP_OBJECT (CfgWnd, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (CfgWnd, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkUseFixes, "checkUseFixes");
  GLADE_HOOKUP_OBJECT (CfgWnd, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (CfgWnd, table3, "table3");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix1, "checkFix1");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix2, "checkFix2");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix3, "checkFix3");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix4, "checkFix4");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix5, "checkFix5");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix6, "checkFix6");
  GLADE_HOOKUP_OBJECT (CfgWnd, checkFix7, "checkFix7");
  GLADE_HOOKUP_OBJECT (CfgWnd, label24, "label24");
  GLADE_HOOKUP_OBJECT (CfgWnd, label25, "label25");
  GLADE_HOOKUP_OBJECT (CfgWnd, label26, "label26");
  GLADE_HOOKUP_OBJECT (CfgWnd, label27, "label27");
  GLADE_HOOKUP_OBJECT (CfgWnd, label28, "label28");
  GLADE_HOOKUP_OBJECT (CfgWnd, label29, "label29");
  GLADE_HOOKUP_OBJECT (CfgWnd, label30, "label30");
  GLADE_HOOKUP_OBJECT (CfgWnd, label12, "label12");
  GLADE_HOOKUP_OBJECT_NO_REF (CfgWnd, tooltips, "tooltips");

  return CfgWnd;
}

GtkWidget*
create_AboutWnd (void)
{
  GtkWidget *AboutWnd;
  GtkWidget *vbox5;
  GtkWidget *vbox6;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label13;

  AboutWnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (AboutWnd), 12);
  gtk_window_set_title (GTK_WINDOW (AboutWnd), _("About X11 Video Plugin"));
  gtk_window_set_modal (GTK_WINDOW (AboutWnd), TRUE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (AboutWnd), vbox5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Coded by: Pete Bernert and the P.E.Op.S. team"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox6), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);

  label3 = gtk_label_new (_("Homepage: http://home.t-online.de/home/PeteBernert/"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox6), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_CENTER);

  label4 = gtk_label_new (_("EMail: BlackDove@addcom.de"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox6), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_CENTER);

  label5 = gtk_label_new (_("Version: 1.15"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox6), label5, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label5, -1, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_CENTER);

  label6 = gtk_label_new (_("Release date: 2003"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox6), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_CENTER);

  label13 = gtk_label_new (_("<b>PCSX-df Video Plugin Adaption</b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (vbox6), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  g_signal_connect ((gpointer) AboutWnd, "destroy",
                    G_CALLBACK (on_AboutWnd_destroy),
                    NULL);

  * Store pointers to all widgets, for use by lookup_widget(). *
  GLADE_HOOKUP_OBJECT_NO_REF (AboutWnd, AboutWnd, "AboutWnd");
  GLADE_HOOKUP_OBJECT (AboutWnd, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (AboutWnd, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (AboutWnd, label2, "label2");
  GLADE_HOOKUP_OBJECT (AboutWnd, label3, "label3");
  GLADE_HOOKUP_OBJECT (AboutWnd, label4, "label4");
  GLADE_HOOKUP_OBJECT (AboutWnd, label5, "label5");
  GLADE_HOOKUP_OBJECT (AboutWnd, label6, "label6");
  GLADE_HOOKUP_OBJECT (AboutWnd, label13, "label13");

  return AboutWnd;
}

*/
