/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 * Warning: I edited this file by hand :P
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_Config (void)
{
  GtkWidget *Config;
  GtkWidget *vbox4;
  GtkWidget *frame1;
  GtkWidget *vbox7;
  GtkWidget *hbox7;
  GSList *Screen_Mode_group = NULL;
  GtkWidget *GtkRadioButton_Fullscreen;
  GtkWidget *GtkCombo_Modes;
  GtkWidget *combo_entry1;
  GtkWidget *hbox8;
  GtkWidget *GtkRadioButton_Windowed;
  GtkWidget *hbox6;
  GtkWidget *label11;
  GtkWidget *GtkEntry_Width;
  GtkWidget *label12;
  GtkWidget *GtkEntry_Height;
  GtkWidget *hbox9;
  GtkWidget *label9;
  GtkWidget *GtkCombo_Stretching;
  GtkWidget *combo_entry2;
  GtkWidget *hbox10;
  GtkWidget *label10;
  GtkWidget *GtkCombo_Dithering;
  GtkWidget *combo_entry3;
  GtkWidget *frame5;
  GtkWidget *vbox8;
  GtkWidget *GtkCheckButton_FPSdisplay;
  GtkWidget *hbox14;
  GtkWidget *vbox10;
  GtkWidget *GtkCheckButton_FPSlimit;
  GtkWidget *GtkCheckButton_FPSskip;
  GtkWidget *vbox11;
  GtkWidget *GtkCheckButton_FPSauto;
  GtkWidget *hbox13;
  GtkWidget *label13;
  GtkWidget *GtkEntry_FPS;
  GtkWidget *label14;
  GtkWidget *frame3;
  GtkWidget *vbox9;
  GtkWidget *GtkCheckButton_Scanlines;
  GtkWidget *hbox15;
  GtkWidget *GtkCheckButton_Fixes;
  GtkWidget *button8;
  GtkWidget *hbox4;
  GtkWidget *frame4;
  GtkWidget *hbuttonbox4;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *hbuttonbox3;
  GtkWidget *button4;
  GtkWidget *button5;

  Config = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (Config), "Config", Config);
  gtk_container_set_border_width (GTK_CONTAINER (Config), 5);
  gtk_window_set_title (GTK_WINDOW (Config), "Configure the P.E.Op.S. PSX X11 Soft Renderer...");
  gtk_window_set_position (GTK_WINDOW (Config), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (Config), FALSE, FALSE, FALSE);

  vbox4 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (Config), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  frame1 = gtk_frame_new ("Resolution");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox4), frame1, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 2);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame1), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 7);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox7, TRUE, TRUE, 0);

  GtkRadioButton_Fullscreen = gtk_radio_button_new_with_label (Screen_Mode_group, "Fullscreen mode");
  Screen_Mode_group = gtk_radio_button_group (GTK_RADIO_BUTTON (GtkRadioButton_Fullscreen));
  gtk_widget_ref (GtkRadioButton_Fullscreen);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkRadioButton_Fullscreen", GtkRadioButton_Fullscreen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkRadioButton_Fullscreen);
  gtk_box_pack_start (GTK_BOX (hbox7), GtkRadioButton_Fullscreen, FALSE, FALSE, 0);

  GtkCombo_Modes = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Modes);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_Modes", GtkCombo_Modes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Modes);
  gtk_box_pack_end (GTK_BOX (hbox7), GtkCombo_Modes, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_Modes, 193, -2);

  combo_entry1 = GTK_COMBO (GtkCombo_Modes)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry1), FALSE);

  hbox8 = gtk_hbox_new (FALSE, 53);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox8, TRUE, TRUE, 0);

  GtkRadioButton_Windowed = gtk_radio_button_new_with_label (Screen_Mode_group, "Windowed mode");
  Screen_Mode_group = gtk_radio_button_group (GTK_RADIO_BUTTON (GtkRadioButton_Windowed));
  gtk_widget_ref (GtkRadioButton_Windowed);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkRadioButton_Windowed", GtkRadioButton_Windowed,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkRadioButton_Windowed);
  gtk_box_pack_start (GTK_BOX (hbox8), GtkRadioButton_Windowed, FALSE, FALSE, 0);

  hbox6 = gtk_hbox_new (FALSE, 10);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (hbox8), hbox6, FALSE, FALSE, 0);

  label11 = gtk_label_new ("Size:");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  GtkEntry_Width = gtk_entry_new ();
  gtk_widget_ref (GtkEntry_Width);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkEntry_Width", GtkEntry_Width,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkEntry_Width);
  gtk_box_pack_start (GTK_BOX (hbox6), GtkEntry_Width, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkEntry_Width, 40, -2);

  label12 = gtk_label_new ("x");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  GtkEntry_Height = gtk_entry_new ();
  gtk_widget_ref (GtkEntry_Height);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkEntry_Height", GtkEntry_Height,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkEntry_Height);
  gtk_box_pack_start (GTK_BOX (hbox6), GtkEntry_Height, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkEntry_Height, 40, -2);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox9, TRUE, TRUE, 0);

  label9 = gtk_label_new ("Stretching mode:");
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label9), 18, 0);

  GtkCombo_Stretching = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Stretching);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_Stretching", GtkCombo_Stretching,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Stretching);
  gtk_box_pack_end (GTK_BOX (hbox9), GtkCombo_Stretching, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_Stretching, 193, -2);

  combo_entry2 = GTK_COMBO (GtkCombo_Stretching)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry2), FALSE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox10);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox10, TRUE, TRUE, 0);

  label10 = gtk_label_new ("Dithering:");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label10), 18, 0);

  GtkCombo_Dithering = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Dithering);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_Dithering", GtkCombo_Dithering,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Dithering);
  gtk_box_pack_end (GTK_BOX (hbox10), GtkCombo_Dithering, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_Dithering, 193, -2);

  combo_entry3 = GTK_COMBO (GtkCombo_Dithering)->entry;
  gtk_widget_ref (combo_entry3);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry3", combo_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry3);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry3), FALSE);

  frame5 = gtk_frame_new ("Framerate");
  gtk_widget_ref (frame5);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame5", frame5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox4), frame5, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame5), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 5);

  GtkCheckButton_FPSdisplay = gtk_check_button_new_with_label ("Show FPS display on startup");
  gtk_widget_ref (GtkCheckButton_FPSdisplay);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_FPSdisplay", GtkCheckButton_FPSdisplay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_FPSdisplay);
  gtk_box_pack_start (GTK_BOX (vbox8), GtkCheckButton_FPSdisplay, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox14, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (hbox14), vbox10, TRUE, TRUE, 0);

  GtkCheckButton_FPSlimit = gtk_check_button_new_with_label ("Use FPS limit");
  gtk_widget_ref (GtkCheckButton_FPSlimit);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_FPSlimit", GtkCheckButton_FPSlimit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_FPSlimit);
  gtk_box_pack_start (GTK_BOX (vbox10), GtkCheckButton_FPSlimit, FALSE, FALSE, 0);

  GtkCheckButton_FPSskip = gtk_check_button_new_with_label ("Use Frame skipping");
  gtk_widget_ref (GtkCheckButton_FPSskip);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_FPSskip", GtkCheckButton_FPSskip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_FPSskip);
  gtk_box_pack_start (GTK_BOX (vbox10), GtkCheckButton_FPSskip, FALSE, FALSE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox14), vbox11, TRUE, TRUE, 0);

  GtkCheckButton_FPSauto = gtk_check_button_new_with_label ("Auto-detect FPS/Frame skipping limit");
  gtk_widget_ref (GtkCheckButton_FPSauto);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_FPSauto", GtkCheckButton_FPSauto,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_FPSauto);
  gtk_box_pack_start (GTK_BOX (vbox11), GtkCheckButton_FPSauto, FALSE, FALSE, 0);

  hbox13 = gtk_hbox_new (FALSE, 10);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox13, TRUE, TRUE, 0);

  label13 = gtk_label_new ("Framerate:");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox13), label13, FALSE, FALSE, 0);

  GtkEntry_FPS = gtk_entry_new ();
  gtk_widget_ref (GtkEntry_FPS);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkEntry_FPS", GtkEntry_FPS,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkEntry_FPS);
  gtk_box_pack_start (GTK_BOX (hbox13), GtkEntry_FPS, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkEntry_FPS, 40, -2);

  label14 = gtk_label_new ("FPS");
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox13), label14, FALSE, FALSE, 0);

  frame3 = gtk_frame_new ("Options");
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox4), frame3, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (frame3), vbox9);
  gtk_container_set_border_width (GTK_CONTAINER (vbox9), 5);

  GtkCheckButton_Scanlines = gtk_check_button_new_with_label ("Maintain 4:3 Aspect Ratio");
  gtk_widget_ref (GtkCheckButton_Scanlines);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Scanlines", GtkCheckButton_Scanlines,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Scanlines);
  gtk_box_pack_start (GTK_BOX (vbox9), GtkCheckButton_Scanlines, FALSE, FALSE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox15, TRUE, TRUE, 0);

  GtkCheckButton_Fixes = gtk_check_button_new_with_label ("Activate special games fixes");
  gtk_widget_ref (GtkCheckButton_Fixes);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Fixes", GtkCheckButton_Fixes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Fixes);
  gtk_box_pack_start (GTK_BOX (hbox15), GtkCheckButton_Fixes, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_label ("...");
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (hbox15), button8, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 5);

  frame4 = gtk_frame_new ("Default Settings");
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (hbox4), frame4, TRUE, TRUE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_container_add (GTK_CONTAINER (frame4), hbuttonbox4);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox4), 0);

  button6 = gtk_button_new_with_label ("Fast");
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  button7 = gtk_button_new_with_label ("Nice");
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (hbox4), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 0);

  button4 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button5 = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (Config), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (OnCfgFixes),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (OnDefFast),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (OnDefNice),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (OnOk),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (OnCancel),
                      NULL);

  return Config;
}

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkWidget *vbox3;
  GtkWidget *GtkLabel_Version;
  GtkWidget *GtkLabel_Date;
  GtkWidget *label8;
  GtkWidget *label2;
  GtkWidget *hbox3;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *hbuttonbox2;
  GtkWidget *button3;

  About = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (About), "About", About);
  gtk_container_set_border_width (GTK_CONTAINER (About), 5);
  gtk_window_set_title (GTK_WINDOW (About), "About the P.E.Op.S. PSX X11 Soft Renderer...");
  gtk_window_set_position (GTK_WINDOW (About), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (About), TRUE);
  gtk_window_set_policy (GTK_WINDOW (About), FALSE, FALSE, FALSE);

  vbox2 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (About), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (About), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  hbox2 = gtk_hbox_new (FALSE, 10);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (About), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  label5 = gtk_label_new ("Version:\nRelease date:\nCoded by:\nPete's EMail:");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (About), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (About), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox3, TRUE, TRUE, 0);

  GtkLabel_Version = gtk_label_new ("xx.xx");
  gtk_widget_ref (GtkLabel_Version);
  gtk_object_set_data_full (GTK_OBJECT (About), "GtkLabel_Version", GtkLabel_Version,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkLabel_Version);
  gtk_box_pack_start (GTK_BOX (vbox3), GtkLabel_Version, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (GtkLabel_Version), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (GtkLabel_Version), 0, 0.5);

  GtkLabel_Date = gtk_label_new ("xx.xx.xxxx");
  gtk_widget_ref (GtkLabel_Date);
  gtk_object_set_data_full (GTK_OBJECT (About), "GtkLabel_Date", GtkLabel_Date,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkLabel_Date);
  gtk_box_pack_start (GTK_BOX (vbox3), GtkLabel_Date, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (GtkLabel_Date), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (GtkLabel_Date), 7.45058e-09, 0.5);

  label8 = gtk_label_new ("Pete Bernert and the P.E.Op.S. team\nBlackDove@addcom.de");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (About), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox3), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label8), 7.45058e-09, 0.5);

  label2 = gtk_label_new ("The P.E.Op.S. SoftGPU team:");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (About), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox2), label2, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 10);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (About), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 5);

  label3 = gtk_label_new ("");
  gtk_label_parse_uline (GTK_LABEL (label3),
                         "P.E.Op.S. page:\n- Pete Bernert\n- Lewpy\n- lu_zero\n- linuzappz\n- syo\n- Darko Matesic");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (About), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  label4 = gtk_label_new ("");
  gtk_label_parse_uline (GTK_LABEL (label4),
                         "https://sourceforge.net/projects/peops\nhttp://www.pbernert.com\nhttp://lewpy.psxemu.com\nhttp://brsk.virtualave.net/lu__zero/\nhttp://www.pcsx.net\nhttp://www.geocities.co.jp/SiliconValley-Bay/2072/\nhttp://mrdario.tripod.com");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (About), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (About), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, TRUE, TRUE, 0);

  button3 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (About), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (About), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (OnAbout_Ok),
                      NULL);

  return About;
}

